// <auto-generated />
using System;
using CashRegister.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CashRegister.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260108165428_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CashRegister.Domain.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BranchCode")
                        .IsUnique();

                    b.ToTable("Branches", (string)null);
                });

            modelBuilder.Entity("CashRegister.Domain.Entities.CashEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AuthorizedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AuthorizedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("date");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("BranchId", "EntryDate")
                        .IsUnique();

                    b.ToTable("CashEntries", (string)null);
                });

            modelBuilder.Entity("CashRegister.Domain.Entities.CashEntryRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Amount10")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Amount100")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Amount1000")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Amount2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Amount20")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Amount200")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Amount5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Amount50")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Amount500")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CashEntryId")
                        .HasColumnType("int");

                    b.Property<decimal>("CoinAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOutflow")
                        .HasColumnType("bit");

                    b.Property<string>("RowType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CashEntryId", "SequenceOrder");

                    b.ToTable("CashEntryRows", (string)null);
                });

            modelBuilder.Entity("CashRegister.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CashRegister.Domain.Entities.CashEntry", b =>
                {
                    b.HasOne("CashRegister.Domain.Entities.User", "AuthorizedBy")
                        .WithMany()
                        .HasForeignKey("AuthorizedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CashRegister.Domain.Entities.Branch", "Branch")
                        .WithMany("CashEntries")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CashRegister.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuthorizedBy");

                    b.Navigation("Branch");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("CashRegister.Domain.Entities.CashEntryRow", b =>
                {
                    b.HasOne("CashRegister.Domain.Entities.CashEntry", "CashEntry")
                        .WithMany("Rows")
                        .HasForeignKey("CashEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CashEntry");
                });

            modelBuilder.Entity("CashRegister.Domain.Entities.User", b =>
                {
                    b.HasOne("CashRegister.Domain.Entities.Branch", "Branch")
                        .WithMany("Users")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("CashRegister.Domain.Entities.Branch", b =>
                {
                    b.Navigation("CashEntries");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CashRegister.Domain.Entities.CashEntry", b =>
                {
                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
